// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/tuna.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Metadata struct {
	Ip              string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	TcpPort         uint32   `protobuf:"varint,2,opt,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
	UdpPort         uint32   `protobuf:"varint,3,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	ServiceId       uint32   `protobuf:"varint,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceTcp      []uint32 `protobuf:"varint,5,rep,packed,name=service_tcp,json=serviceTcp" json:"service_tcp,omitempty"`
	ServiceUdp      []uint32 `protobuf:"varint,6,rep,packed,name=service_udp,json=serviceUdp" json:"service_udp,omitempty"`
	Price           string   `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	BeneficiaryAddr string   `protobuf:"bytes,8,opt,name=beneficiary_addr,json=beneficiaryAddr,proto3" json:"beneficiary_addr,omitempty"`
}

func (m *Metadata) Reset()      { *m = Metadata{} }
func (*Metadata) ProtoMessage() {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_tuna_c3674ba1f821682b, []int{0}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return m.Size()
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Metadata) GetTcpPort() uint32 {
	if m != nil {
		return m.TcpPort
	}
	return 0
}

func (m *Metadata) GetUdpPort() uint32 {
	if m != nil {
		return m.UdpPort
	}
	return 0
}

func (m *Metadata) GetServiceId() uint32 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *Metadata) GetServiceTcp() []uint32 {
	if m != nil {
		return m.ServiceTcp
	}
	return nil
}

func (m *Metadata) GetServiceUdp() []uint32 {
	if m != nil {
		return m.ServiceUdp
	}
	return nil
}

func (m *Metadata) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Metadata) GetBeneficiaryAddr() string {
	if m != nil {
		return m.BeneficiaryAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*Metadata)(nil), "pb.Metadata")
}
func (this *Metadata) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Metadata)
	if !ok {
		that2, ok := that.(Metadata)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Ip != that1.Ip {
		return false
	}
	if this.TcpPort != that1.TcpPort {
		return false
	}
	if this.UdpPort != that1.UdpPort {
		return false
	}
	if this.ServiceId != that1.ServiceId {
		return false
	}
	if len(this.ServiceTcp) != len(that1.ServiceTcp) {
		return false
	}
	for i := range this.ServiceTcp {
		if this.ServiceTcp[i] != that1.ServiceTcp[i] {
			return false
		}
	}
	if len(this.ServiceUdp) != len(that1.ServiceUdp) {
		return false
	}
	for i := range this.ServiceUdp {
		if this.ServiceUdp[i] != that1.ServiceUdp[i] {
			return false
		}
	}
	if this.Price != that1.Price {
		return false
	}
	if this.BeneficiaryAddr != that1.BeneficiaryAddr {
		return false
	}
	return true
}
func (this *Metadata) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&pb.Metadata{")
	s = append(s, "Ip: "+fmt.Sprintf("%#v", this.Ip)+",\n")
	s = append(s, "TcpPort: "+fmt.Sprintf("%#v", this.TcpPort)+",\n")
	s = append(s, "UdpPort: "+fmt.Sprintf("%#v", this.UdpPort)+",\n")
	s = append(s, "ServiceId: "+fmt.Sprintf("%#v", this.ServiceId)+",\n")
	s = append(s, "ServiceTcp: "+fmt.Sprintf("%#v", this.ServiceTcp)+",\n")
	s = append(s, "ServiceUdp: "+fmt.Sprintf("%#v", this.ServiceUdp)+",\n")
	s = append(s, "Price: "+fmt.Sprintf("%#v", this.Price)+",\n")
	s = append(s, "BeneficiaryAddr: "+fmt.Sprintf("%#v", this.BeneficiaryAddr)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTuna(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Metadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Metadata) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTuna(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	if m.TcpPort != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintTuna(dAtA, i, uint64(m.TcpPort))
	}
	if m.UdpPort != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintTuna(dAtA, i, uint64(m.UdpPort))
	}
	if m.ServiceId != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintTuna(dAtA, i, uint64(m.ServiceId))
	}
	if len(m.ServiceTcp) > 0 {
		dAtA2 := make([]byte, len(m.ServiceTcp)*10)
		var j1 int
		for _, num := range m.ServiceTcp {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x2a
		i++
		i = encodeVarintTuna(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if len(m.ServiceUdp) > 0 {
		dAtA4 := make([]byte, len(m.ServiceUdp)*10)
		var j3 int
		for _, num := range m.ServiceUdp {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		dAtA[i] = 0x32
		i++
		i = encodeVarintTuna(dAtA, i, uint64(j3))
		i += copy(dAtA[i:], dAtA4[:j3])
	}
	if len(m.Price) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintTuna(dAtA, i, uint64(len(m.Price)))
		i += copy(dAtA[i:], m.Price)
	}
	if len(m.BeneficiaryAddr) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintTuna(dAtA, i, uint64(len(m.BeneficiaryAddr)))
		i += copy(dAtA[i:], m.BeneficiaryAddr)
	}
	return i, nil
}

func encodeVarintTuna(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func NewPopulatedMetadata(r randyTuna, easy bool) *Metadata {
	this := &Metadata{}
	this.Ip = string(randStringTuna(r))
	this.TcpPort = uint32(r.Uint32())
	this.UdpPort = uint32(r.Uint32())
	this.ServiceId = uint32(r.Uint32())
	v1 := r.Intn(10)
	this.ServiceTcp = make([]uint32, v1)
	for i := 0; i < v1; i++ {
		this.ServiceTcp[i] = uint32(r.Uint32())
	}
	v2 := r.Intn(10)
	this.ServiceUdp = make([]uint32, v2)
	for i := 0; i < v2; i++ {
		this.ServiceUdp[i] = uint32(r.Uint32())
	}
	this.Price = string(randStringTuna(r))
	this.BeneficiaryAddr = string(randStringTuna(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyTuna interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneTuna(r randyTuna) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringTuna(r randyTuna) string {
	v3 := r.Intn(100)
	tmps := make([]rune, v3)
	for i := 0; i < v3; i++ {
		tmps[i] = randUTF8RuneTuna(r)
	}
	return string(tmps)
}
func randUnrecognizedTuna(r randyTuna, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldTuna(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldTuna(dAtA []byte, r randyTuna, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateTuna(dAtA, uint64(key))
		v4 := r.Int63()
		if r.Intn(2) == 0 {
			v4 *= -1
		}
		dAtA = encodeVarintPopulateTuna(dAtA, uint64(v4))
	case 1:
		dAtA = encodeVarintPopulateTuna(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateTuna(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateTuna(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateTuna(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateTuna(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Metadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovTuna(uint64(l))
	}
	if m.TcpPort != 0 {
		n += 1 + sovTuna(uint64(m.TcpPort))
	}
	if m.UdpPort != 0 {
		n += 1 + sovTuna(uint64(m.UdpPort))
	}
	if m.ServiceId != 0 {
		n += 1 + sovTuna(uint64(m.ServiceId))
	}
	if len(m.ServiceTcp) > 0 {
		l = 0
		for _, e := range m.ServiceTcp {
			l += sovTuna(uint64(e))
		}
		n += 1 + sovTuna(uint64(l)) + l
	}
	if len(m.ServiceUdp) > 0 {
		l = 0
		for _, e := range m.ServiceUdp {
			l += sovTuna(uint64(e))
		}
		n += 1 + sovTuna(uint64(l)) + l
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovTuna(uint64(l))
	}
	l = len(m.BeneficiaryAddr)
	if l > 0 {
		n += 1 + l + sovTuna(uint64(l))
	}
	return n
}

func sovTuna(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTuna(x uint64) (n int) {
	return sovTuna(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Metadata) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Metadata{`,
		`Ip:` + fmt.Sprintf("%v", this.Ip) + `,`,
		`TcpPort:` + fmt.Sprintf("%v", this.TcpPort) + `,`,
		`UdpPort:` + fmt.Sprintf("%v", this.UdpPort) + `,`,
		`ServiceId:` + fmt.Sprintf("%v", this.ServiceId) + `,`,
		`ServiceTcp:` + fmt.Sprintf("%v", this.ServiceTcp) + `,`,
		`ServiceUdp:` + fmt.Sprintf("%v", this.ServiceUdp) + `,`,
		`Price:` + fmt.Sprintf("%v", this.Price) + `,`,
		`BeneficiaryAddr:` + fmt.Sprintf("%v", this.BeneficiaryAddr) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTuna(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Metadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTuna
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Metadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Metadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTuna
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTuna
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TcpPort", wireType)
			}
			m.TcpPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTuna
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TcpPort |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UdpPort", wireType)
			}
			m.UdpPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTuna
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UdpPort |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceId", wireType)
			}
			m.ServiceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTuna
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ServiceId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTuna
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ServiceTcp = append(m.ServiceTcp, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTuna
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTuna
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTuna
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ServiceTcp = append(m.ServiceTcp, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceTcp", wireType)
			}
		case 6:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTuna
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ServiceUdp = append(m.ServiceUdp, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTuna
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTuna
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTuna
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ServiceUdp = append(m.ServiceUdp, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceUdp", wireType)
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTuna
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTuna
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeneficiaryAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTuna
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTuna
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeneficiaryAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTuna(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTuna
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTuna(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTuna
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTuna
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTuna
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTuna
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTuna
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTuna(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTuna = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTuna   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("pb/tuna.proto", fileDescriptor_tuna_c3674ba1f821682b) }

var fileDescriptor_tuna_c3674ba1f821682b = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0x3f, 0x4e, 0x2b, 0x31,
	0x10, 0x06, 0xf0, 0x9d, 0xcd, 0xcb, 0x3f, 0x3f, 0x05, 0xd0, 0x8a, 0xc2, 0x20, 0x31, 0x44, 0x54,
	0xa1, 0x20, 0x29, 0x68, 0x69, 0xa0, 0xa3, 0x40, 0x42, 0x11, 0xd4, 0xd1, 0xae, 0xed, 0x04, 0x17,
	0xc4, 0x23, 0x63, 0x23, 0xd1, 0x71, 0x04, 0x8e, 0xc1, 0x11, 0x38, 0x02, 0x65, 0xca, 0x94, 0xac,
	0xd3, 0x50, 0x46, 0x54, 0x94, 0x08, 0x6f, 0x22, 0x85, 0xce, 0xdf, 0xfc, 0xbe, 0x91, 0xac, 0x61,
	0x1d, 0x2a, 0x06, 0xce, 0x4f, 0xf3, 0x3e, 0x59, 0xe3, 0x4c, 0x96, 0x52, 0xb1, 0x7f, 0x32, 0xd1,
	0xee, 0xce, 0x17, 0x7d, 0x61, 0xee, 0x07, 0x13, 0x33, 0x31, 0x83, 0x48, 0x85, 0x1f, 0xc7, 0x14,
	0x43, 0x7c, 0x55, 0x2b, 0x47, 0x5f, 0xc0, 0x5a, 0x57, 0xca, 0xe5, 0x32, 0x77, 0x79, 0xb6, 0xc5,
	0x52, 0x4d, 0x1c, 0xba, 0xd0, 0x6b, 0x0f, 0x53, 0x4d, 0xd9, 0x1e, 0x6b, 0x39, 0x41, 0x23, 0x32,
	0xd6, 0xf1, 0xb4, 0x0b, 0xbd, 0xce, 0xb0, 0xe9, 0x04, 0x5d, 0x1b, 0xeb, 0x7e, 0xc9, 0xcb, 0x15,
	0xd5, 0x2a, 0xf2, 0xb2, 0xa2, 0x03, 0xc6, 0x1e, 0x94, 0x7d, 0xd4, 0x42, 0x8d, 0xb4, 0xe4, 0xff,
	0x22, 0xb6, 0x57, 0x93, 0x4b, 0x99, 0x1d, 0xb2, 0xff, 0x6b, 0x76, 0x82, 0x78, 0xbd, 0x5b, 0xeb,
	0x75, 0x86, 0xeb, 0x8d, 0x1b, 0x41, 0x9b, 0x05, 0x2f, 0x89, 0x37, 0xfe, 0x14, 0x6e, 0x25, 0x65,
	0xbb, 0xac, 0x4e, 0x56, 0x0b, 0xc5, 0x9b, 0xf1, 0xa7, 0x55, 0xc8, 0x8e, 0xd9, 0x4e, 0xa1, 0xa6,
	0x6a, 0xac, 0x85, 0xce, 0xed, 0xd3, 0x28, 0x97, 0xd2, 0xf2, 0x56, 0x2c, 0x6c, 0x6f, 0xcc, 0xcf,
	0xa5, 0xb4, 0x17, 0x67, 0xb3, 0x12, 0x93, 0x79, 0x89, 0xc9, 0xb2, 0x44, 0xf8, 0x2e, 0x11, 0x9e,
	0x03, 0xc2, 0x6b, 0x40, 0x78, 0x0b, 0x08, 0xef, 0x01, 0x61, 0x16, 0x10, 0x3e, 0x02, 0xc2, 0x67,
	0xc0, 0x64, 0x19, 0x10, 0x5e, 0x16, 0x98, 0xcc, 0x16, 0x98, 0xcc, 0x17, 0x98, 0x14, 0x8d, 0x78,
	0xb9, 0xd3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x02, 0x4c, 0x31, 0x7d, 0x01, 0x00, 0x00,
}
