// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/tuna.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EncryptionAlgo int32

const (
	EncryptionAlgo_ENCRYPTION_NONE              EncryptionAlgo = 0
	EncryptionAlgo_ENCRYPTION_XSALSA20_POLY1305 EncryptionAlgo = 1
	EncryptionAlgo_ENCRYPTION_AES_GCM           EncryptionAlgo = 2
)

var EncryptionAlgo_name = map[int32]string{
	0: "ENCRYPTION_NONE",
	1: "ENCRYPTION_XSALSA20_POLY1305",
	2: "ENCRYPTION_AES_GCM",
}
var EncryptionAlgo_value = map[string]int32{
	"ENCRYPTION_NONE":              0,
	"ENCRYPTION_XSALSA20_POLY1305": 1,
	"ENCRYPTION_AES_GCM":           2,
}

func (x EncryptionAlgo) String() string {
	return proto.EnumName(EncryptionAlgo_name, int32(x))
}
func (EncryptionAlgo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tuna_aa10095f6cda5e27, []int{0}
}

type ConnectionMetadata struct {
	EncryptionAlgo           EncryptionAlgo `protobuf:"varint,1,opt,name=encryption_algo,json=encryptionAlgo,proto3,enum=pb.EncryptionAlgo" json:"encryption_algo,omitempty"`
	PublicKey                []byte         `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Nonce                    []byte         `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	IsMeasurement            bool           `protobuf:"varint,4,opt,name=is_measurement,json=isMeasurement,proto3" json:"is_measurement,omitempty"`
	MeasurementBytesDownlink uint32         `protobuf:"varint,5,opt,name=measurement_bytes_downlink,json=measurementBytesDownlink,proto3" json:"measurement_bytes_downlink,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}       `json:"-"`
	XXX_unrecognized         []byte         `json:"-"`
	XXX_sizecache            int32          `json:"-"`
}

func (m *ConnectionMetadata) Reset()         { *m = ConnectionMetadata{} }
func (m *ConnectionMetadata) String() string { return proto.CompactTextString(m) }
func (*ConnectionMetadata) ProtoMessage()    {}
func (*ConnectionMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_tuna_aa10095f6cda5e27, []int{0}
}
func (m *ConnectionMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionMetadata.Unmarshal(m, b)
}
func (m *ConnectionMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionMetadata.Marshal(b, m, deterministic)
}
func (dst *ConnectionMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionMetadata.Merge(dst, src)
}
func (m *ConnectionMetadata) XXX_Size() int {
	return xxx_messageInfo_ConnectionMetadata.Size(m)
}
func (m *ConnectionMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionMetadata proto.InternalMessageInfo

func (m *ConnectionMetadata) GetEncryptionAlgo() EncryptionAlgo {
	if m != nil {
		return m.EncryptionAlgo
	}
	return EncryptionAlgo_ENCRYPTION_NONE
}

func (m *ConnectionMetadata) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ConnectionMetadata) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *ConnectionMetadata) GetIsMeasurement() bool {
	if m != nil {
		return m.IsMeasurement
	}
	return false
}

func (m *ConnectionMetadata) GetMeasurementBytesDownlink() uint32 {
	if m != nil {
		return m.MeasurementBytesDownlink
	}
	return 0
}

type ServiceMetadata struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	TcpPort              uint32   `protobuf:"varint,2,opt,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
	UdpPort              uint32   `protobuf:"varint,3,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	ServiceId            uint32   `protobuf:"varint,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceTcp           []uint32 `protobuf:"varint,5,rep,packed,name=service_tcp,json=serviceTcp,proto3" json:"service_tcp,omitempty"`
	ServiceUdp           []uint32 `protobuf:"varint,6,rep,packed,name=service_udp,json=serviceUdp,proto3" json:"service_udp,omitempty"`
	Price                string   `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	BeneficiaryAddr      string   `protobuf:"bytes,8,opt,name=beneficiary_addr,json=beneficiaryAddr,proto3" json:"beneficiary_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceMetadata) Reset()         { *m = ServiceMetadata{} }
func (m *ServiceMetadata) String() string { return proto.CompactTextString(m) }
func (*ServiceMetadata) ProtoMessage()    {}
func (*ServiceMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_tuna_aa10095f6cda5e27, []int{1}
}
func (m *ServiceMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceMetadata.Unmarshal(m, b)
}
func (m *ServiceMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceMetadata.Marshal(b, m, deterministic)
}
func (dst *ServiceMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceMetadata.Merge(dst, src)
}
func (m *ServiceMetadata) XXX_Size() int {
	return xxx_messageInfo_ServiceMetadata.Size(m)
}
func (m *ServiceMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceMetadata proto.InternalMessageInfo

func (m *ServiceMetadata) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ServiceMetadata) GetTcpPort() uint32 {
	if m != nil {
		return m.TcpPort
	}
	return 0
}

func (m *ServiceMetadata) GetUdpPort() uint32 {
	if m != nil {
		return m.UdpPort
	}
	return 0
}

func (m *ServiceMetadata) GetServiceId() uint32 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *ServiceMetadata) GetServiceTcp() []uint32 {
	if m != nil {
		return m.ServiceTcp
	}
	return nil
}

func (m *ServiceMetadata) GetServiceUdp() []uint32 {
	if m != nil {
		return m.ServiceUdp
	}
	return nil
}

func (m *ServiceMetadata) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *ServiceMetadata) GetBeneficiaryAddr() string {
	if m != nil {
		return m.BeneficiaryAddr
	}
	return ""
}

type StreamMetadata struct {
	ServiceId            uint32   `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	PortId               uint32   `protobuf:"varint,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	IsPayment            bool     `protobuf:"varint,3,opt,name=is_payment,json=isPayment,proto3" json:"is_payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMetadata) Reset()         { *m = StreamMetadata{} }
func (m *StreamMetadata) String() string { return proto.CompactTextString(m) }
func (*StreamMetadata) ProtoMessage()    {}
func (*StreamMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_tuna_aa10095f6cda5e27, []int{2}
}
func (m *StreamMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMetadata.Unmarshal(m, b)
}
func (m *StreamMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMetadata.Marshal(b, m, deterministic)
}
func (dst *StreamMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMetadata.Merge(dst, src)
}
func (m *StreamMetadata) XXX_Size() int {
	return xxx_messageInfo_StreamMetadata.Size(m)
}
func (m *StreamMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMetadata proto.InternalMessageInfo

func (m *StreamMetadata) GetServiceId() uint32 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *StreamMetadata) GetPortId() uint32 {
	if m != nil {
		return m.PortId
	}
	return 0
}

func (m *StreamMetadata) GetIsPayment() bool {
	if m != nil {
		return m.IsPayment
	}
	return false
}

func init() {
	proto.RegisterType((*ConnectionMetadata)(nil), "pb.ConnectionMetadata")
	proto.RegisterType((*ServiceMetadata)(nil), "pb.ServiceMetadata")
	proto.RegisterType((*StreamMetadata)(nil), "pb.StreamMetadata")
	proto.RegisterEnum("pb.EncryptionAlgo", EncryptionAlgo_name, EncryptionAlgo_value)
}

func init() { proto.RegisterFile("pb/tuna.proto", fileDescriptor_tuna_aa10095f6cda5e27) }

var fileDescriptor_tuna_aa10095f6cda5e27 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0x49, 0x4b, 0xff, 0x2e, 0x24, 0xad, 0x0c, 0x02, 0x83, 0x18, 0x11, 0x55, 0x42, 0x2a,
	0x2c, 0xca, 0x30, 0x23, 0x56, 0xb0, 0x09, 0xa5, 0x42, 0x15, 0xd3, 0x1f, 0x25, 0x83, 0xc4, 0xac,
	0x2c, 0xc7, 0x36, 0x95, 0x35, 0xad, 0x6d, 0x39, 0x0e, 0x28, 0xcf, 0xcc, 0x13, 0xb0, 0x43, 0x49,
	0x3a, 0x25, 0x65, 0x79, 0xcf, 0x77, 0x6c, 0x9d, 0x63, 0x5f, 0xf0, 0x4d, 0xfa, 0xd6, 0xe5, 0x8a,
	0x4e, 0x8d, 0xd5, 0x4e, 0xa3, 0x96, 0x49, 0xc7, 0xbf, 0x3d, 0x40, 0x33, 0xad, 0x94, 0x60, 0x4e,
	0x6a, 0xb5, 0x14, 0x8e, 0x72, 0xea, 0x28, 0xfa, 0x00, 0x43, 0xa1, 0x98, 0x2d, 0x4c, 0xa9, 0x12,
	0xba, 0xdb, 0x6a, 0xec, 0x85, 0xde, 0x24, 0xb8, 0x40, 0x53, 0x93, 0x4e, 0xe7, 0x47, 0x14, 0xed,
	0xb6, 0x3a, 0x0e, 0xc4, 0xc9, 0x8c, 0xce, 0x00, 0x4c, 0x9e, 0xee, 0x24, 0x23, 0xb7, 0xa2, 0xc0,
	0xad, 0xd0, 0x9b, 0x3c, 0x8c, 0x07, 0xb5, 0xf2, 0x55, 0x14, 0xe8, 0x31, 0x74, 0x94, 0x56, 0x4c,
	0xe0, 0x76, 0x45, 0xea, 0x01, 0xbd, 0x82, 0x40, 0x66, 0x64, 0x2f, 0x68, 0x96, 0x5b, 0xb1, 0x17,
	0xca, 0xe1, 0xfb, 0xa1, 0x37, 0xe9, 0xc7, 0xbe, 0xcc, 0x96, 0xff, 0x44, 0xf4, 0x11, 0x9e, 0x37,
	0x3c, 0x24, 0x2d, 0x9c, 0xc8, 0x08, 0xd7, 0xbf, 0xd4, 0x4e, 0xaa, 0x5b, 0xdc, 0x09, 0xbd, 0x89,
	0x1f, 0xe3, 0x86, 0xe3, 0x53, 0x69, 0xf8, 0x7c, 0xe0, 0xe3, 0x3f, 0x1e, 0x0c, 0x13, 0x61, 0x7f,
	0x4a, 0x26, 0x8e, 0x55, 0x03, 0x68, 0x49, 0x53, 0xb5, 0x1b, 0xc4, 0x2d, 0x69, 0xd0, 0x33, 0xe8,
	0x3b, 0x66, 0x88, 0xd1, 0xd6, 0x55, 0xd9, 0xfd, 0xb8, 0xe7, 0x98, 0xd9, 0x68, 0xeb, 0x4a, 0x94,
	0xf3, 0x03, 0x6a, 0xd7, 0x28, 0xe7, 0x35, 0x3a, 0x03, 0xc8, 0xea, 0x8b, 0x89, 0xe4, 0x55, 0x74,
	0x3f, 0x1e, 0x1c, 0x94, 0x05, 0x47, 0x2f, 0xe1, 0xc1, 0x1d, 0x76, 0xcc, 0xe0, 0x4e, 0xd8, 0x9e,
	0xf8, 0xf1, 0xdd, 0x89, 0x6b, 0x66, 0x9a, 0x86, 0x9c, 0x1b, 0xdc, 0x3d, 0x31, 0x7c, 0xe3, 0xa6,
	0x7c, 0x35, 0x63, 0x25, 0x13, 0xb8, 0x57, 0x25, 0xad, 0x07, 0xf4, 0x1a, 0x46, 0xa9, 0x50, 0xe2,
	0x87, 0x64, 0x92, 0xda, 0x82, 0x50, 0xce, 0x2d, 0xee, 0x57, 0x86, 0x61, 0x43, 0x8f, 0x38, 0xb7,
	0xe3, 0x2d, 0x04, 0x89, 0xb3, 0x82, 0xee, 0x8f, 0xcd, 0x4f, 0x33, 0x7b, 0xff, 0x67, 0x7e, 0x0a,
	0xbd, 0xb2, 0x69, 0xc9, 0xea, 0x77, 0xe8, 0x96, 0xe3, 0x82, 0x97, 0xe7, 0x64, 0x46, 0x0c, 0x2d,
	0xaa, 0x6f, 0x6a, 0x57, 0xdf, 0x34, 0x90, 0xd9, 0xa6, 0x16, 0xde, 0x10, 0x08, 0x4e, 0x17, 0x04,
	0x3d, 0x82, 0xe1, 0x7c, 0x35, 0x8b, 0x6f, 0x36, 0xd7, 0x8b, 0xf5, 0x8a, 0xac, 0xd6, 0xab, 0xf9,
	0xe8, 0x1e, 0x0a, 0xe1, 0x45, 0x43, 0xfc, 0x9e, 0x44, 0x57, 0x49, 0x74, 0x71, 0x4e, 0x36, 0xeb,
	0xab, 0x9b, 0x77, 0x97, 0xe7, 0xef, 0x47, 0x1e, 0x7a, 0x02, 0xa8, 0xe1, 0x88, 0xe6, 0x09, 0xf9,
	0x32, 0x5b, 0x8e, 0x5a, 0x69, 0xb7, 0x5a, 0xdf, 0xcb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x04,
	0x26, 0x68, 0x72, 0xcf, 0x02, 0x00, 0x00,
}
